:Title: OGC PubSub SWG
:titletext: OGC PubSub SWG
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments
:dwg_review: Architecture DWG
:dwg_review_meeting: September 2023 OGC Member Meeting
:githubrepo: https://github.com/opengeospatial/pubsub

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: 2023-06-08
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    10-182r4
|Category: OGC(R) Standards Working Group Charter
|Authors:   Chris Little
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2023 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

////
Version of 2018-12-12
Some Instructions
This document is the template to be used for proposing the formation of a new Standards Working Group (SWG).

The first step is to complete the SWG Charter for the proposed new SWG.

The next step is to email the draft SWG charter to the Technical Committee Chair (TCC).  The TCC will review the draft charter and make any necessary comments and provide guidance.

Finally, once the Charter is ready, the SWG charter will be posted to the OGC Pending Documents and the vote process in the Technical Committee Policies and Procedures will start.

Any questions, please contact OGC staff.
////

To: OGC members & interested parties

A new OGC Standards Working Group is being formed. The OGC members listed below have proposed the {titletext}.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

The purpose of the {titletext} is to define an OGC Implementation Standard that enables publish/subscribe functionality for resources supported by OGC API Standards in a well-defined manner.

== Business value proposition

////
This section provides a statement describing the value of this standards activity in relation to the OGC Membership, the geospatial community, and the wider IT community. This statement can be in terms of the interoperability problem being solved, processing Change requests to meet market (and Member requirements), a policy requirement and/or some other business value proposition. The proposition described in this section does not have to be in economic terms.
////

OGC API Standards specify Web based capabilities which are typically based on polling for collection resource updates (new or changed or deleted features/records, coverages, maps, data, etc.). Depending on a collection's temporal resolution or frequency of updates or size, an event-driven / Publish-Subscribe architecture provides a timely, efficient and low latency approach for delivery of data updates or notifications.

== Scope of work

The SWG shall review existing material, e.g. in form of OGC Engineering Reports and Standards (both OGC and external), to produce a version 1.0 implementation standard that clearly defines how to enable publish/subscribe functionality for implementations of OGC API Standards in a common way. The standard may be specified as a single part or as a multi-part standard. If applicable, this standard may become a future part of the OGC API - Common standard. 

The items that need to be addressed by the SWG include:

. Write a core requirements class that clearly defines the requirements for enabling publish/subscribe functionality.
. Write a requirements class to publish the definition of an event-driven API with AsyncAPI.
. Write one or more additional requirements classes that define how to realize the core publish/subscribe functionality for a specific service binding (MQTT, AMQP, Kafka, etc.) – for the bindings the SWG decides to support in the initial version of the standard.
. Write extension documents that define how to integrate publish/subscribe functionality with OGC API Standards
. Write extension documents that define baseline payloads for publish/subscribe services
. Develop examples and – if necessary to enable core functionality – conceptual models and their JSON Schema implementation (e.g. for notification metadata).
. Address any other technical and/or editorial issues that arise during the review period.

The Standard will include security considerations.

Only those functional requirements and comments submitted through the formal process as identified in the Policy and Procedures shall be addressed. Items suggested through emails, vocal discussions, etc. will be outside of the scope of this SWG unless the SWG decides to include them.

NOTE: The management of subscriptions is out of scope of Part 1, but will be considered for future extensions.

=== Statement of relationship of planned work to the current OGC Standards baseline

////
This section describes the relationship of the proposed standards activity to the existing Standards baseline. For the 3 cases:
If defining a new Standard, a statement of the relationship to the existing Standards baseline including statements related to overlap (if any) with existing OGC Standards functionality, harmonization issues, and so forth.

If processing change requests and performing a revision to an existing Standard, a simple statement to this effect shall be made.

If processing a draft submission of a specification developed outside the OGC process, a clear statement of the relationship to the existing Standards baseline including statements related to overlap (if any) with existing OGC Standards functionality, harmonization issues, and so forth. This information is provided to allow a focus of the discussion on criteria for considering any new solution that may be incompatible with older ones, overlaps existing functionality in the current baseline, and criteria for either deprecating older solutions, or simultaneously endorsing more than one option.
////

This proposed standard is intended to be a major component of the OGC API framework. The proposed standard will take advantage of Web API patterns identified in OGC API standards (e.g., MQTT in OGC SensorThings API) and other ongoing API efforts (e.g. AsyncAPI) to better align with current and emerging IT practices.

=== What is out of scope?

The scope of the {titletext} is confined to enabling basic publish/subscribe functionality for resources from existing and future OGC API Standards. Any other requirement or functionality the SWG decides to be not contributing to core publish/subscribe functionality is also out of scope.

=== Specific existing work used as starting point

The starting point for this implementation standard shall be the "Discussion Paper for Publish-Subscribe Workflow in OGC
APIs" (OGC 23-013). This charter also recognizes the prior work done for OGC Web Services (OWS) as specified in the OGC® Publish/Subscribe Interface Standard 1.0 - Core Standard (OGC 13-131r1). 

=== Is this a persistent SWG

[x] YES

[ ] NO

=== When can the SWG be inactivated

The {titletext} shall be inactivated after the following milestones have been achieved:

* The SWG has reviewed input provided by the OGC and perhaps other communities.
* The SWG produced the candidate standards listed below.
* SWG membership approves a recommendation to submit the documents to the TC for consideration as OGC Adopted Standards.
* The candidate standards have been approved by the OGC Technical and Executive Planning Committees as OGC Adopted Standards.

== Description of deliverables

////
This section describes what the deliverables will be for this SWG activity. Deliverables could be a revision to an existing Standard, including revisions to schemas. A deliverable could also be a best practices document.

This section also includes a preliminary schedule of activities. For example, an RFC focused SWG schedule would provide a plan and schedule that includes the start date, target date for release of the candidate Standard for public review, date for consolidation of comments, date for edits to document based on comments, and a final target date for making a recommendation to the Membership. This information will be made public and will also be used as input to a RoadMap for the document. Therefore, the more detail the better.
////

=== Initial deliverables

There shall be at least two deliverables:

. A document describing the core requirements regarding the support of publish-subscribe functionality in implementations of OGC API Standards.
. A document describing how to implement these core requirements for each of the bindings the SWG decides to support. At least one such document will be produced by the SWG.

The SWG may also decide to cover both deliverables in a single document.

=== Additional SWG tasks

The SWG may decide to work on additional bindings in new parts of the standard.

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated audience / participants

Any organization that has a requirement for enabling clients to subscribe to a resource that is published by an implementation of an OGC API Standard and of interest to the client and to have the API notify the client when such data is available. Also, organizations that want to enable Event Architecture as well as Event Processing functionality in their computing environment.

In general, all geospatial service providers / end users that have a need to publish/receive notifications about events of interest as soon as they are detected.

== Domain Working Group endorsement

////
The SWG will list all Domain Working Groups (DWGs) in which the SWG formation was discussed and/or chartered. If a DWG has specifically endorsed the formation of the SWG, then a statement of endorsement should be included.
////

The {dwg_review} will review the proof-of-concept at {githubrepo} and this SWG charter. A statement of endorsement is anticipated at the {dwg_review_meeting}.

== Other informative information about the work of this SWG

=== Collaboration

////
Describe the work environment of the SWG, including the use of GitHub or GitLab.
////

=== Similar or applicable standards work (OGC and elsewhere)

The following standards and projects may be relevant to the SWG's planned work, although none currently provide all the functionality anticipated by this committee's deliverables:

* OGC 06-121r3, OpenGIS® Web Services Common Standard
* IETF, Request for Comments (RFC) 4287, The Atom Syndication Format (“Atom 1.0”), December 2005, http://www.ietf.org/rfc/rfc4287.txt[http://www.ietf.org/rfc/rfc4287.txt]
* IETF, Request for Comments (RFC) 3920, Extensible Messaging and Presence Protocol (XMPP): Core, http://tools.ietf.org/html/rfc3920[http://tools.ietf.org/html/rfc3920] 
* XML Base, XML Base (Second Addition), W3C Recommendation 28 January 2009, http://www.w3.org/TR/xmlbase/[http://www.w3.org/TR/xmlbase/]
* OGC 09-001, SWE Service Model Standard
* OGC 06-028r3, Sensor Alert Service Best Practices
* OGC 09-000, Sensor Planning Service 2.0
* OGC 06-095, Web Notification Service Best Practices
* OGC 08-133, Sensor Event Service Discussion Paper
* OGC 08-132, Event Pattern Markup Language Discussion Paper
* OGC 09-032, OWS-6 SWE Event Architecture Engineering Report
* OGC 09-050r1, OWS-6 AIM Engineering Report
* OGC 10-061r1, OWS-7 Dynamic Sensor Notification Engineering Report
* OGC 10-073r1, OWS-7 CCSI-SWE Best Practices Engineering Report
* OGC 10-060r1, OWS-7 Event Architecture Engineering Report
* OGC 10-079r3, OWS-7 Aviation Architecture Engineering Report
* OGC 10-069r2, OWS-7 Geosynchronization service
* OASIS WS-Notification v1.3, http://www.oasis-open.org/committees/tc_home.php?wg_abbrev=wsn[http://www.oasis-open.org/committees/tc_home.php?wg_abbrev=wsn]
* W3C Member Submission 20060315, Web Services Eventing Submission (WS-Eventing), http://www.w3.org/Submission/2006/SUBM-WS-Eventing-20060315[http://www.w3.org/Submission/2006/SUBM-WS-Eventing-20060315]
* OGC® Publish/Subscribe Interface Standard 1.0 - Core, https://docs.ogc.org/is/13-131r1/13-131r1.html[(OGC 13-131r1)]
* OGC® Publish/Subscribe Interface Standard 1.0 SOAP Protocol Binding Extension, https://docs.ogc.org/is/13-133r1/13-133r1.html[(OGC 13-133r1)]


=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. Extend the table as necessary.

|====
|Name | Email| Organization
| Panagiotis (Peter) A. Vretanos | mailto:panagiotis.vretanos@mariadb.com[panagiotis.vretanos@mariadb.com]| MariaDB
| Chris Little| mailto:chris.little@metoffice.gov.uk[chris.little@metoffice.gov.uk]| Met Office
| Steve Olson| mailto:steve.r.olson@noaa.gov[steve.r.olson@noaa.gov]| NOAA
| Tom Kralidis| mailto:tom.kralidis@ec.gc.ca[tom.kralidis@ec.gc.ca]| Meteorological Service of Canada
| Clemens Portele| mailto:portele@interactive-instruments.de[portele@interactive-instruments.de]| interactive instruments
| FirstName LastName| mailto:example@example.org[example@example.org]| Example
| FirstName LastName| mailto:example@example.org[example@example.org]| Example
| FirstName LastName| mailto:example@example.org[example@example.org]| Example
| FirstName LastName| mailto:example@example.org[example@example.org]| Example
|====

=== Conveners

* Panagiotis (Peter) A. Vretanos
* Chris Little

=== Background

This section is from the 2010 charter and may not get carried over into the 2023 recharter.

The Sensor Web Enablement (SWE) initiative definition of the Sensor Alert Service (SAS) specification was the first step in developing an OGC Standard that defines publish/subscribe functionality for all OGC Web Services (OWS). The development of SAS continued until 2007 and resulted in a Best Practices document. The SAS was not released as OGC Standard. One reason for this was that the SAS defined its own publish/subscribe interface. OGC members rightly requested that the SAS should make use of existing standards to enable publish/subscribe.

This request led to the development of the Sensor Event Service (SES) engineering specification. Like the SAS, the SES was designed as a broker between notification producers (e.g. sensors) and notification consumers (e.g. client applications or other services). In contrast to the SAS, the SES used the Web Services Notification (WS-N) standards from OASIS for achieving the publish/subscribe functionality. The SES document was released as an OGC Discussion Paper in 2008. Due to the experience gained with the development of the SES, WS-N was also selected to be used in the SWE Service Model (SWES) for performing publish/subscribe in the SOAP binding. The Sensor Planning Service (SPS) 2.0 depends upon SWES and thus also uses WS-N for enabling publish/subscribe functionality in its SOAP binding.

In 2009, in the OWS-6 testbed, the first version of the Event Architecture (EA) was developed. This work built on the experiences in developing the SAS and the SES engineering specifications but the focus for the EA was not on the development of a service specification. The resulting OWS-6 public Engineering Report (09-032) describes an abstract event architecture including the definition of important terms, an application schema for events and roles and interfaces for the abstract architecture – including interfaces for subscribing for and receiving notifications. This abstract architecture was also mapped to multiple use cases and OGC services to show how it could be applied in various OWSs. In addition related problems and technologies are described like common messaging patterns, event processing, acknowledgements of events and canceling of events.

Work on a cross-thread Event Architecture continued in OWS-7. The resulting report (10-060r1) defines the actual publish / subscribe functionality in much more detail.

In the development of the Event Architecture, Web Services Eventing (WS-E) and ATOM were also considered, besides WS-N. WS-E from the W3C has a similar scope as WS-N but differs in some aspects. WS-E is currently proposed as W3C standard but not released as W3C Recommendation yet.

There are three ATOM internet RFCs. The first is the Atom Syndication Format (ASF) which is an XML based format for the description of lists of related information (feeds). The Atom Publishing Protocol (AtomPub) is used for editing and publishing web resources encoded as ATOM feeds. PubSubHubBub (PSHB) is a protocol that extends ATOM feeds to support push based communication via feeds instead of pulling (requesting) information updates. ATOM feeds have successfully been used in the Geosynchronization work that was performed in OWS-7.

Based upon the experiences made so far regarding the enablement of publish/subscribe in OWS, the OWS PubSub SWG will develop an OGC Standard that supports the requirements regarding PubSub in OWS. Furthermore, this Standard will define in detail how existing Standards that are well used in the IT domain are to be used to enable publish/subscribe functionality in OGC services.


== References

////
Optional list of references.
////
