[[discovery-section]]
== Requirements Class Discovery

=== Overview

include::../requirements/requirements_class_discovery.adoc[]

Event-driven workflows provide Publish-Subscribe based capabilities as part of information systems and architectures. The Publish-Subscribe model also provides efficiencies in providing data "as it happens", thereby preventing potential clients from continuously polling to check on the availability of new data or resources.

The Open Geospatial Consortium (OGC) has conducted significant work on event-based models and architectures. The Publish-Subscribe model results in less network traffic and more timely responses to manage event-based models such as urgent, temporally unpredictable data (examples include, but are not limited to: traffic conditions, weather or hazard warnings, and real-time sensor data).

Building on the OGC Publish-Subscribe Interface Standard https://docs.ogc.org/is/13-131r1/13-131r1.html[OGC 13-131r1], as well as the recommendations put forward in the OGC Pub/Sub White Paper [OGC 20-081] produced as part of OGC Testbed 12, as well as the Discussion paper for Publish-Subscribe workflow in OGC APIs [OGC 23-013], the https://www.opengis.net/doc/IS/ogcapi-edr-2/1.0[OGC API - Environmental Data Retrieval - Part 2: Publish-Subscribe Workflow Standard] discusses approaches for integrating Publish-Subscribe architecture into the OGC API suite of Standards.

include::../recommendations/discovery/PER_protocols.adoc[]

=== OGC API considerations

The OGC API building block approach would typically be used for shared components in API implementations in support of a polling workflow. Using HTTP, this means that the client initiates and invokes requests and receives responses from the server.  A key concept of the OGC API building blocks architecture is the service endpoint of the URL path specifying a resource and any similar sub-resources, which can be applied for Pub/Sub workflow as follows:

* Data producers: Messages are published to a broker, applied to a given channel (example: ``collections/mycollection``).
* Broker provisioning: Published messages are sent to subscribers.
* Subscribers and data consumers: Messages are received by users subscribed to one or more channels (explicitly or using wildcards or filtering).

The above workflow requires adherence to a structure of information channels, auto-discovery of those channels, as well as processing of generic messages for broad interoperability by all components.

=== Links from OGC API to AsyncAPI

Based on research and testing, the Pub/Sub White Paper recommended the use of AsyncAPI. AsyncAPI provides an event-driven equivalent of what is provided by OpenAPI for OGC API Standards (description of protocols, channels, parameters, models, etc.). An implementation of the https://ogcapi.ogc.org/common/overview.html[OGC API landing page requirements class] can provide a link to an AsyncAPI document as follows:

.OGC API landing page example link to an AsyncAPI document
[source,json]
----
{
    "rel": "service-desc",
    "type": "application/asyncapi+json",
    "title": "AsyncAPI document",
    "href": "https://example.org/asyncapi?f=json"
}
----

.OGC API landing page example link to an AsyncAPI document for human consumption
[source,json]
----
{
    "rel": "service-doc",
    "type": "text/html",
    "title": "AsyncAPI document",
    "href": "https://example.org/asyncapi?f=html"
}
----

To provide a link to a specific collection's events, an AsyncAPI URI fragment is used to address a specific channel.

.Example of OGC API Pub/Sub link to an AsyncAPI document addressing a specific channel
[source,json]
----
{
    "rel": "items",
    "title": "Data notifications",
    "href": "https://example.org/asyncapi.json#/channels/notify-collections"
}
----

This allows a client to navigate to the relevant channel object in the AsyncAPI document, bind to the channel/topic and have apriori access to the schema of the message payload as needed.

include::../requirements/discovery/REQ_links-from-ogcapi-to-asyncapi.adoc[]
include::../recommendations/discovery/PER_links-from-ogcapi-to-asyncapi.adoc[]

=== Links from AsyncAPI to OGC API

In the above case, an OGC API advertises an AsyncAPI service via a link.  For Pub/Sub and AsyncAPI discovery workflow, an ``x-ogc-link`` object is made available to be able to refer the OGC API equivalent for the given resource.

.AsyncAPI ``x-ogc-link`` example link to an OGC API endpoint/resource
[source,yaml]
----
notify-collections:
    address: collections
    x-ogc-link:
        type: application/json
        rel: data
        href: https://api.example.org/collections
    messages:
        collection_msg:
            description: collection updated notification
            payload:
                $ref: '#/components/schemas/collection_msg'
----

include::../requirements/discovery/REQ_links-from-asyncapi-to-ogcapi.adoc[]

=== Links from OpenAPI to AsyncAPI

Given OGC APIs utilize OpenAPI to describe a API, an ``x-ogc-link`` can be made available to refer to the Pub/Sub equivalent for the given resource.  In addition, an ``x-ogc-linkTemplate`` object can be used when referring to an AsyncAPI fragment that includes https://www.asyncapi.com/docs/reference/specification/v3.0.0#channel-address-expressions[channel address expressions].

.OpenAPI ``x-ogc-linkTemplate`` example link to an AsyncAPI fragment with a channel address expression
[source,json]
----
{
    "/collections/discovery-metadata/items": {
        "get": {
            "description": "Discovery metadata records",
            "operationId": "getDiscoveryMetadataItems",
        ...
        },
        "x-ogc-linkTemplate": {
            "uriTemplate": "https://example.org/asyncapi.json#/channels/{collectionId}"
        }
}
----

include::../requirements/discovery/REQ_links-from-openapi-to-asyncapi.adoc[]

=== Links from OGC API to Pub/Sub resources

The links array could also provide references to the Pub/Sub capabilities available on the service. A *collection* link could reference a collection update notification channel.

NOTE:  In the OGC API Suite of Standards, a https://docs.ogc.org/DRAFTS/20-024.html#collection-description[collection] is a geospatial https://docs.ogc.org/DRAFTS/20-024.html#resource-definition[resource] (such as a dataset) that may be available as one or more sub-resource https://docs.ogc.org/DRAFTS/20-024.html#distribution-definition[distributions] that conform to one or more OGC API standards. See the https://docs.ogc.org/DRAFTS/20-024.html#rc-collections-section[OGC API - Common - Part 2: Geospatial Data candidate Standard].

Communicating event driven workflow from a link object is made via the `+hub+` link relation.  This link relation communicates that the link represents a Publish-Subscribe workflow defined by a Pub/Sub protocol in the `href` property as well as a `channel` property.  The `channel` property provides the relevant addressable topic that a client can subscribe to after connecting to a Pub/Sub endpoint.  The value and syntax of the `channel` property is bound to the Pub/Sub protocol identified in the `href` property.

.Example of OGC API Pub/Sub link to a Pub/Sub broker
[source,json]
----
{
    "rel": "hub",
    "title": "Data notifications",
    "href": "mqtt://example.org:8883",
}
----

An *items* link could reference a data payload channel:

An OGC API - Features example

.Example of OGC API - Features linking to a data payload channel
[source,json]
----
{
    "rel": "hub",
    "title": "Data notifications",
    "href": "mqtt://example.org:8883",
    "channel": "collections/surface-weather-observations"
}
----

An OGC API - EDR example

.Example of OGC API - EDR linking to a data payload channel
[source,json]
----
{
    "rel": "hub",
    "title": "Data notifications",
    "href": "mqtt://example.org:8883",
    "channel": "collections/surface-weather-observations/items"
}
----

include::../requirements/discovery/REQ_links-from-ogcapi-to-pubsub.adoc[]
include::../recommendations/discovery/PER_links-from-ogcapi-to-pubsub.adoc[]

=== Client side filtering

In some cases, users may wish to filter message payloads (when not possible via a channel or topic structure), to process payloads matching given criteria. AsyncAPI natively supports this use case by describing a channel's message payload using JSON Schema, thereby allowing for apriori knowledge of the payload when developing client applications.

.AsyncAPI example of message payload definition
[source,yaml]
----
notify-collections:
    address: collections
    messages:
        collection_msg:
            description: collection updated notification
            payload:
                $ref: '#/components/schemas/collection_msg'
components:
    schemas:
        collection_msg:
            type: object
            properties:
                id:
                    type: string
                    description: identifier
                title:
                    type: string
                    description: title of collection
            required:
                - id
----

By inspecting the message payload definition in the AsyncAPI channel, a client can perform the following workflows against messages when subscribed to the relevant channel:

* JSON Schema validation
* Evaluating each message based on a property (for example, searching the ``title`` property in the above example for a certain string pattern or regular expression)

include::../recommendations/discovery/REC_client-side-filtering.adoc[]
